[tasks.test]
run = [
  { task = "test:server" },
  { task = "test:client" },
  { task = "test:format" },
  { task = "test:lint" },
  { task = "test:typecheck" },
]

[tasks."test:server"]
run = "npx vitest --config ./.config/vitest.server.ts"

[tasks."test:client"]
run = "npx vitest --config ./.config/vitest.client.ts"

[tasks."test:format"]
run = "npx oxfmt --config ./.config/.oxfmtrc.json --check"

[tasks."test:lint"]
run = "npx oxlint --config ./.config/.oxlintrc.json"

[tasks."test:typecheck"]
run = [
  "npx tsc --noEmit --project ./.config/tsconfig.base.json",
  "npx tsc --noEmit --project ./.config/tsconfig.test.json",
  "npx tsc --noEmit --project ./.config/tsconfig.client.json",
  "npx tsc --noEmit --project ./.config/tsconfig.server.json",
  "npx tsc --noEmit --project ./.config/tsconfig.config.json",
]

[tasks.fmt]
run = "npx oxfmt --config ./.config/.oxfmtrc.json"

[tasks.lint]
run = "npx oxlint --config ./.config/.oxlintrc.json"

[tasks.update]
run = [
  "npx npm-check-updates --target minor -u --cooldown 7",
  "pnpm install",
  "pnpm dlx playwright install --with-deps",
]
